version: '3'

services:
  basketapi:
    image: eshop/basket.api
    build:
      context: /source/AppDev-ContainerDemo/sample-apps/eShopOnContainers/src/Services/Basket/Basket.API
      dockerfile: Dockerfile
    
  catalogapi:
    image: eshop/catalog.api
    build:
      context: /source/AppDev-ContainerDemo/sample-apps/eShopOnContainers/src/Services/Catalog/Catalog.API
      dockerfile: Dockerfile
    
  identityapi:
    image: eshop/identity.api
    build:
      context: /source/AppDev-ContainerDemo/sample-apps/eShopOnContainers/src/Services/Identity/Identity.API
      dockerfile: Dockerfile
    
  orderingapi:
    image: eshop/ordering.api
    build:
      context: /source/AppDev-ContainerDemo/sample-apps/eShopOnContainers/src/Services/Ordering/Ordering.API
      dockerfile: Dockerfile

  webmvc:
    image: eshop/webmvc
    build:
      context: /source/AppDev-ContainerDemo/sample-apps/eShopOnContainers/src/Web/WebMVC
      dockerfile: Dockerfile
    
  sqldata:
    image: microsoft/mssql-server-linux
    
  basketdata:
    image: redis
    ports:
      - "6379:6379"
    
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8081:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"