version: '3'

# The Production docker-compose file has to have the external/real IPs or DNS names for the services 
# The ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like: 
#     ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP=192.168.88.248
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.
#
# Set ASPNETCORE_ENVIRONMENT=Development to get errors while testing. 
#
# You need to start it with the following CLI command: 
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:

  basketapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5103
      - ConnectionString=basketdata
      - identityUrl=http://identityapi:5105              #Local: You need to open your host's firewall at range 5100-5105.  at range 5100-5105. 
    ports:
      - "5103:5103"

  catalogapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5101
      - ConnectionString=Server=sqldata;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word
      - ExternalCatalogBaseUrl=http://VALUEOF-UNIQUE-SERVER-PREFIX-iaas-demo.eastus.cloudapp.azure.com:5101    #Local: You need to open your host's firewall at range 5100-5105.  at range 5100-5105.
    ports:
      - "5101:5101"

  identityapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5105
      - SpaClient=http://VALUEOF-UNIQUE-SERVER-PREFIX-iaas-demo.eastus.cloudapp.azure.com:5104
      - ConnectionStrings__DefaultConnection=Server=sqldata;Database=Microsoft.eShopOnContainers.Service.IdentityDb;User Id=sa;Password=Pass@word 
      - MvcClient=http://VALUEOF-UNIQUE-SERVER-PREFIX-iaas-demo.eastus.cloudapp.azure.com:5100              #Local: You need to open your host's firewall at range 5100-5105.  
    ports:
      - "5105:5105"

  orderingapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5102
      - ConnectionString=Server=sqldata;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass@word
      - identityUrl=http://identityapi:5105              #Local: You need to open your host's firewall at range 5100-5105.  at range 5100-5105. 
    ports:
      - "5102:5102"

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5100
      - CatalogUrl=http://catalogapi:5101
      - OrderingUrl=http://orderingapi:5102
      - IdentityUrl=http://VALUEOF-UNIQUE-SERVER-PREFIX-iaas-demo.eastus.cloudapp.azure.com:5105     #Local: Use VALUEOF-UNIQUE-SERVER-PREFIX-iaas-demo.eastus.cloudapp.azure.com, if using external IP or DNS name from browser.          
      - BasketUrl=http://basketapi:5103
    ports:
      - "5100:5100"

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"