---
# This playbook builds the .NET Website & creates a container --> pushes to the private repo and then pulls it down
- hosts: buildbox
  remote_user: VALUEOF-DEMO-ADMIN-USER-NAME

  tasks: 
  - name: Restore the requirements
    command: dotnet restore
    args:
      chdir: /source/AppDev-ContainerDemo/sample-apps/aspnet-core-linux/src
  
  - name: .NET BUILD
    command: dotnet build
    args:
      chdir: /source/AppDev-ContainerDemo/sample-apps/aspnet-core-linux/src
  
  - name: Publish the site
    command: dotnet publish
    args:
      chdir: /source/AppDev-ContainerDemo/sample-apps/aspnet-core-linux/src

  - name: Build the DOCKER image
    command: ~/bin/docker-compose -f docker-stack.yml build
    become: true
    args:
      chdir: /source/AppDev-ContainerDemo/sample-apps/aspnet-core-linux/demo/iaas-swarm/

  - name: Tag the DOCKER image
    command: docker tag ossdemo/aspnet-core-linux VALUEOF-REGISTRY-SERVER-NAME/ossdemo/aspnet-core-linux
    become: true

  - name: Log into private registry and force re-authorization
    command: docker login VALUEOF-REGISTRY-SERVER-NAME -u VALUEOF-REGISTRY-USER-NAME -p VALUEOF-REGISTRY-PASSWORD
    become: true

  - name: Push to the Azure Private Registry
    command: docker push VALUEOF-REGISTRY-SERVER-NAME/ossdemo/aspnet-core-linux
    become: true

#Now deploy the containers on the SWARM CLUSTER

  - name: Push to the SWARM cluster
    command: docker stack deploy --compose-file docker-stack.yml aspnet --with-registry-auth
    become: true
    args:
      chdir: /source/AppDev-ContainerDemo/sample-apps/aspnet-core-linux/demo/iaas-swarm
