---
- hosts: all
  remote_user: VALUEOF-DEMO-ADMIN-USER-NAME
  sudo: true

  tasks:
    - name: Get OMS Agent Executable
      get_url: 
        url: https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh
        dest: /etc/onboard_agent.sh
        
    - name: Install and Configure Agent
      shell: sudo sh /etc/onboard_agent.sh -w VALUEOF-REPLACE-OMS-WORKSPACE -s VALUEOF-REPLACE-OMS-PRIMARYKEY -d opinsights.azure.com

#OMS Service MAP
    - name: Get OMS Service Map
      get_url: 
        url: https://aka.ms/dependencyagentlinux
        dest: /etc/InstallDependencyAgent-Linux64.bin
    
    - name: Turn file into executable
      command: chmod +x /etc/InstallDependencyAgent-Linux64.bin

    - name: Install and Configure OMS Service Mapping Tool
      command: /etc/InstallDependencyAgent-Linux64.bin -s

#Start the monitoring container - we dont need this as the agent should already be installed across the board.
    # - name: Start the monitoring container for Application Insights if not already running
    #   command: docker run -v /var/run/docker.sock:/docker.sock --name=AppInsightMonitoring -d microsoft/applicationinsights ikey=VALUEOF-APPLICATION-INSIGHTS-ASPNETCORELINUX-KEY 
    #   become: true
    #   ignore_errors: true