---
# This playbook builds the .NET Website & creates a container --> pushes to the private repo and then pulls it down
- hosts: buildbox
  remote_user: gbbossdemo

  tasks: 
  - name: Restore the requirements
    command: dotnet restore
    args:
      chdir: /source/AppDev-ContainerDemo/sample-apps/aspnet-core-linux/src
  
  - name: .NET BUILD
    command: dotnet build
    args:
      chdir: /source/AppDev-ContainerDemo/sample-apps/aspnet-core-linux/src
  
  - name: Publish the site
    command: dotnet publish
    args:
      chdir: /source/AppDev-ContainerDemo/sample-apps/aspnet-core-linux/src

   #delete existing container, Build, Tag and Publish
  - name: Delete the existing DOCKER container
    command: docker image rm gbbossdemo/aspnet-core-linux
    become: true
    ignore_errors: true

  - name: Delete the existing DOCKER image  - Save Space
    command: docker rmi gbbossdemo/aspnet-core-linux -f
    become: true
    ignore_errors: true
    
  - name: Delete the existing DOCKER registry image  - Save Space
    command: docker rmi gbbossdemo/aspnet-core-linux -f
    become: true
    ignore_errors: true

  - name: Build the DOCKER image
    command: docker build -t gbbossdemo/aspnet-core-linux .
    become: true
    args:
      chdir: /source/AppDev-ContainerDemo/sample-apps/aspnet-core-linux/src

  - name: Tag the DOCKER image
    command: docker tag gbbossdemo/aspnet-core-linux VALUEOF-REGISTRY-SERVER-NAME/gbbossdemo/aspnet-core-linux
    become: true

  - name: Log into private registry and force re-authorization
    command: docker login VALUEOF-REGISTRY-SERVER-NAME -u VALUEOF-REGISTRY-USER-NAME -p VALUEOF-REGISTRY-PASSWORD
    become: true

  - name: Push to the Azure Private Registry
    command: docker push VALUEOF-REGISTRY-SERVER-NAME/gbbossdemo/aspnet-core-linux
    become: true

#Now deploy the containers on the worker nodes

- hosts: dockerhosts
  remote_user: gbbossdemo
  sudo : true 

  tasks: 
  - name: Log into private registry and force re-authorization
    command: docker login VALUEOF-REGISTRY-SERVER-NAME -u VALUEOF-REGISTRY-USER-NAME -p VALUEOF-REGISTRY-PASSWORD
    become: true

  - name: Kill the existing DOCKER container
    command: docker rm aspnet-core-linux -f
    become: true
    ignore_errors: true

  - name: Kill the existing DOCKER Image
    command: docker rmi aspnet-core-linux -f
    become: true
    ignore_errors: true

  - name: Pull the new DOCKER container
    command: docker pull VALUEOF-REGISTRY-SERVER-NAME/gbbossdemo/aspnet-core-linux
    become: true

  - name: Start the DOCKER container
    command: docker run -d -p 80:80 --name=aspnet-core-linux VALUEOF-REGISTRY-SERVER-NAME/gbbossdemo/aspnet-core-linux
    become: true

  - name: Start the monitoring container for Application Insights if not already running
    command: docker run -v /var/run/docker.sock:/docker.sock --name=AppInsightMonitoring -d microsoft/applicationinsights ikey=VALUEOF-APPLICATION-INSIGHTS-KEY 
    become: true
    ignore_errors: true
