---
# This playbook builds the .NET Website & creates a container --> pushes to the private repo and then pulls it down
- hosts: buildbox
  remote_user: VALUEOF-DEMO-ADMIN-USER-NAME

  tasks: 
  - name: Build the DOCKER image
    command: docker build -t ossdemo/nodejs-todo-docdb .
    become: true
    args:
      chdir: /source/AppDev-ContainerDemo/sample-apps/nodejs-todo/src

  - name: Tag the DOCKER image
    command: docker tag ossdemo/node-todo-docdb VALUEOF-REGISTRY-SERVER-NAME/ossdemo/nodejs-todo-docdb
    become: true

  - name: Log into private registry and force re-authorization
    command: docker login VALUEOF-REGISTRY-SERVER-NAME -u VALUEOF-REGISTRY-USER-NAME -p VALUEOF-REGISTRY-PASSWORD
    become: true

  - name: Push to the Azure Private Registry
    command: docker push VALUEOF-REGISTRY-SERVER-NAME/ossdemo/nodejs-todo-docdb
    become: true