---
# This playbook installs docker on all the hosts
- name: Install Docker
  hosts: rhelrunners
  remote_user: GBBOSSDemo
  sudo : true 


  tasks: 
#  - name: update YUM
#    yum: name=* state=latest

   # This playbook installs and configures all the items necessary for building out the demo's'
  - name: install docker
    yum: name=docker state=latest
  
  - name: enable the extras repo and install epel
    command: yum --enablerepo=extras install epel-release -y
  
  - name: install the latest version of PIP
    yum: name=python-pip state=latest
  
  - name: install docker-py
    pip: name=docker-py version=1.9
  
  - name: Start docker
    service: 
      name: docker 
      state: running
      enabled: yes

#Be Sure to call the OMS-Deploy playbook as well